# Generated by Django 4.1 on 2022-10-14 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=150, verbose_name='Models')),
                ('model_location', models.CharField(max_length=50, verbose_name='location')),
                ('model_file_name', models.CharField(max_length=50, verbose_name='Models file')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
